In [1]:
import pandas as pd

In [10]:
path='../data/processed/01_FULL_raw_table.csv'
raw_df = pd.read_csv(path)


def make_final_base_table(raw_df, country):
    # creamos un nuevo df con las columnas necesarias más una
    df = raw_df[['country', 'title', 'age', 'gender']]

    df = df.rename(columns={'country': 'Country',
                            'title': 'Job Title',
                            'age': 'Age',
                            'gender': 'Quantity'
                            })
    
    # se añade una columna sobre gender con la cuenta de pais, job, tabajo
    df = df.groupby(['Country', 'Job Title', 'Age']).agg('count').reset_index()

    # Si no se mete valor, devuelve el df tal cual.
    if country == 'all':
        df['Percentage'] = df['Quantity'] / df['Country'].count() * 100
        df = df.sort_values(by=['Percentage'], ascending=False)
        return df

    # Si se mete valor, hace un filtro y recalcula el porcentaje.
    else:
        filter_country = df['Country'] == country
        df = df[filter_country]
        df['Percentage'] = df['Quantity'] / df['Country'].count() * 100
        df = df.sort_values(by=['Percentage'], ascending=False)
        return df


def pretty_df_percentage(df):
    df['Percentage'] = df['Percentage'].round(2).apply(lambda x : str(x)+'%')
    return df

def main_table_ch1 (raw_df,pais='all'):
    table = make_final_base_table(raw_df,pais)
    final_table = pretty_df_percentage(table)

    FILES_BASE_PATH = '../data/results/'
    name = FILES_BASE_PATH + 'challenge1.csv'
    final_table.to_csv(name, index=False)

    return final_table

In [16]:
main_table_ch1(raw_df,'France')

,Country,Job Title,Age,Quantity,Percentage
1464,France,No Full-Time Job,40,25,3.6%
1444,France,No Full-Time Job,20,25,3.6%
1442,France,No Full-Time Job,18,22,3.17%
1443,France,No Full-Time Job,19,19,2.74%
1449,France,No Full-Time Job,25,17,2.45%
1467,France,No Full-Time Job,43,16,2.31%
1469,France,No Full-Time Job,45,16,2.31%
1465,France,No Full-Time Job,41,15,2.16%
1445,France,No Full-Time Job,21,15,2.16%
1453,France,No Full-Time Job,29,14,2.02%
1447,France,No Full-Time Job,23,13,1.87%
1452,France,No Full-Time Job,28,13,1.87%
1479,France,No Full-Time Job,55,13,1.87%
1456,France,No Full-Time Job,32,12,1.73%
1446,France,No Full-Time Job,22,12,1.73%
1441,France,No Full-Time Job,17,12,1.73%
1440,France,No Full-Time Job,16,12,1.73%
1474,France,No Full-Time Job,50,12,1.73%
1460,France,No Full-Time Job,36,12,1.73%
1483,France,No Full-Time Job,59,11,1.59%
1439,France,No Full-Time Job,15,11,1.59%
1470,France,No Full-Time Job,46,11,1.59%
1451,France,No Full-Time Job,27,11,1.59%
1450,France,No Full-Time Job,26,11,1.59%
1476,France,No Full-Time Job,52,10,1.44%
1471,France,No Full-Time Job,47,10,1.44%
1468,France,No Full-Time Job,44,10,1.44%
1461,France,No Full-Time Job,37,10,1.44%
1472,France,No Full-Time Job,48,10,1.44%
1473,France,No Full-Time Job,49,9,1.3%
...,...,...,...,...,...
1085,France,Data Security Administrator,45,1,0.14%
1074,France,Data Scientist,21,1,0.14%
1086,France,Data Security Administrator,46,1,0.14%
1089,France,Data Security Analyst,41,1,0.14%
1090,France,Data Security Analyst,42,1,0.14%
1091,France,Data Security Analyst,46,1,0.14%
1092,France,Data Security Analyst,47,1,0.14%
1093,France,Data Security Analyst,50,1,0.14%
1094,France,Data Security Analyst,51,1,0.14%
1075,France,Data Scientist,39,1,0.14%
1073,France,Data Scientist,16,1,0.14%
1055,France,Data Processing Systems Analyst,35,1,0.14%
1063,France,Data Processing Systems Project Planner,35,1,0.14%
1056,France,Data Processing Systems Analyst,41,1,0.14%
1057,France,Data Processing Systems Analyst,45,1,0.14%
1058,France,Data Processing Systems Analyst,48,1,0.14%
1059,France,Data Processing Systems Analyst,50,1,0.14%
1060,France,Data Processing Systems Analyst,51,1,0.14%
1061,France,Data Processing Systems Analyst,56,1,0.14%
1062,France,Data Processing Systems Project Planner,27,1,0.14%
1064,France,Data Processing Systems Project Planner,40,1,0.14%
1072,France,Data Sciences Director,31,1,0.14%
1065,France,Data Processing Systems Project Planner,44,1,0.14%
1066,France,Data Processing Systems Project Planner,45,1,0.14%
1067,France,Data Processing Systems Project Planner,50,1,0.14%
1068,France,Data Processing Systems Project Planner,56,1,0.14%
1069,France,Data Recovery Planner,27,1,0.14%
1070,France,Data Recovery Planner,45,1,0.14%
1071,France,Data Reduction Technician,50,1,0.14%
1514,France,Voice and Data Technician,35,1,0.14%